/** Document Storage API API for storing, retrieving, updating, and deleting JSON documents.
  *
  * OpenAPI spec version: 1.1.0
  *
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator.
  *
  * https://openapi-generator.tech
  */

// this model was generated using model.mustache
package kind.onboarding.docstore.model
import ujson.Value
import scala.util.control.NonFatal

// see https://com-lihaoyi.github.io/upickle/
import upickle.default.{ReadWriter => RW, macroRW}
import upickle.default.*

case class CompareDocuments200Response(
    differences: Option[Value] = None
) {

  def asJson: String = asData.asJson

  def asData: CompareDocuments200ResponseData = {
    CompareDocuments200ResponseData(
      differences = differences.getOrElse(ujson.Null)
    )
  }

}

object CompareDocuments200Response {

  given RW[CompareDocuments200Response] = CompareDocuments200ResponseData.readWriter
    .bimap[CompareDocuments200Response](_.asData, _.asModel)

  enum Fields(fieldName: String) extends Field(fieldName) {
    case differences extends Fields("differences")
  }

}
