/** Document Storage API API for storing, retrieving, updating, and deleting JSON documents.
  *
  * OpenAPI spec version: 1.1.0
  *
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator.
  *
  * https://openapi-generator.tech
  */

// this model was generated using model.mustache
package kind.onboarding.docstore.model
import scala.util.control.NonFatal

// see https://com-lihaoyi.github.io/upickle/
import upickle.default.{ReadWriter => RW, macroRW}
import upickle.default.*

case class CopyDocumentRequest(
    /* The source path of the document */
    from: Option[String] = None,

    /* The destination path of the document */
    to: Option[String] = None
) {

  def asJson: String = asData.asJson

  def asData: CopyDocumentRequestData = {
    CopyDocumentRequestData(
      from = from.getOrElse(""),
      to = to.getOrElse("")
    )
  }

}

object CopyDocumentRequest {

  given RW[CopyDocumentRequest] =
    CopyDocumentRequestData.readWriter.bimap[CopyDocumentRequest](_.asData, _.asModel)

  enum Fields(fieldName: String) extends Field(fieldName) {
    case from extends Fields("from")
    case to   extends Fields("to")
  }

}
