/** Document Storage API API for storing, retrieving, updating, and deleting JSON documents.
  *
  * OpenAPI spec version: 1.1.0
  *
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator.
  *
  * https://openapi-generator.tech
  */

// this model was generated using model.mustache
package kind.onboarding.docstore.model
import scala.util.control.NonFatal

// see https://com-lihaoyi.github.io/upickle/
import upickle.default.{ReadWriter => RW, macroRW}
import upickle.default.*

case class GetDocument404Response(
    message: Option[String] = None
) {

  def asJson: String = asData.asJson

  def asData: GetDocument404ResponseData = {
    GetDocument404ResponseData(
      message = message.getOrElse("")
    )
  }

}

object GetDocument404Response {

  given RW[GetDocument404Response] =
    GetDocument404ResponseData.readWriter.bimap[GetDocument404Response](_.asData, _.asModel)

  enum Fields(fieldName: String) extends Field(fieldName) {
    case message extends Fields("message")
  }

}
