/** Document Storage API API for storing, retrieving, updating, and deleting JSON documents.
  *
  * OpenAPI spec version: 1.1.0
  *
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator.
  *
  * https://openapi-generator.tech
  */

// this model was generated using model.mustache
package kind.onboarding.docstore.model
import java.time.OffsetDateTime
import scala.util.control.NonFatal

// see https://com-lihaoyi.github.io/upickle/
import upickle.default.{ReadWriter => RW, macroRW}
import upickle.default.*

case class GetMetadata200Response(
    lastUpdated: Option[OffsetDateTime] = None,
    latestVersion: Option[String] = None
) {

  def asJson: String = asData.asJson

  def asData: GetMetadata200ResponseData = {
    GetMetadata200ResponseData(
      lastUpdated = lastUpdated.getOrElse(null),
      latestVersion = latestVersion.getOrElse("")
    )
  }

}

object GetMetadata200Response {

  given RW[GetMetadata200Response] =
    GetMetadata200ResponseData.readWriter.bimap[GetMetadata200Response](_.asData, _.asModel)

  enum Fields(fieldName: String) extends Field(fieldName) {
    case lastUpdated   extends Fields("lastUpdated")
    case latestVersion extends Fields("latestVersion")
  }

}
