artifactId: kind-docstore
artifactVersion: "0.2.0"
groupId: kind
packageName: kind.onboarding.docstore
modelPackage: kind.onboarding.docstore.model
apiPackage: kind.onboarding.docstore.api
gitRepoId: onboarding-backend
gitUserId: aaronp