version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  server-built:
    image: porpoiseltd/kind-docstore-db:latest
    container_name: server-built
    depends_on:
      - database
    ports:
      - "8081:8080"
    environment:
      - DATABASE=admin
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=example

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - database
    ports:
      - "8082:8080"
    environment:
      - DATABASE=admin
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=example
