//> using scala "3.3.1"
//> using lib "com.lihaoyi::cask:0.9.2"
//> using lib "com.lihaoyi::scalatags:0.8.2"
/** Document Storage API API for storing, retrieving, updating, and deleting JSON documents.
  *
  * OpenAPI spec version: 1.1.0
  *
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator.
  *
  * https://openapi-generator.tech
  */

// this file was generated from app.mustache
package kind.onboarding.docstore

import _root_.kind.onboarding.docstore.model.*
import _root_.kind.onboarding.docstore.api.*

/** This trait encapsulates the business logic (services) and the http routes which handle the http
  * requests sent to those services.
  *
  * There are default 'not implemented' implementations for the service.
  *
  * If you wanted fine-grained control over the routes and services, you could extend the
  * cask.MainRoutes and mix in this trait by using this:
  *
  * \{\{\{ override def allRoutes = appRoutes \}\}\}
  *
  * More typically, however, you would extend the 'BaseApp' class
  */
trait AppRoutes {
  def appDefaultService: DefaultService = DefaultService()
  def routeForDefault: DefaultRoutes    = DefaultRoutes(appDefaultService)

  def appRoutes = Seq(
    routeForDefault
  )
}
