//> using scala "3.3.1"
//> using lib "com.lihaoyi::cask:0.9.2"
//> using lib "com.lihaoyi::scalatags:0.8.2"
/** Document Storage API API for storing, retrieving, updating, and deleting JSON documents.
  *
  * OpenAPI spec version: 1.1.0
  *
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator.
  *
  * https://openapi-generator.tech
  */

// this file was generated from app.mustache
package kind.onboarding.docstore

import _root_.kind.onboarding.docstore.model.*
import _root_.kind.onboarding.docstore.api.*

/** This is an example of how you might extends BaseApp for a runnable application.
  *
  * See the README.md for how to create your own app
  */
object ExampleApp extends BaseApp() {
  start()
}
